CREATE SCHEMA IF NOT EXISTS TASKANA;

SET SCHEMA TASKANA;

CREATE TABLE HISTORY_EVENTS(
        ID CHAR(40) NOT NULL,
        BUSINESSPROCESSID VARCHAR(64) NULL,
        TASKID VARCHAR(64) NULL,
        EVENTTYPE VARCHAR(64) NULL,
        CREATED TIMESTAMP NULL,
        USERID VARCHAR(64) NULL,
        DOMAIN VARCHAR(64) NULL,
        WORKBASKETKEY VARCHAR(64) NULL,
        PRIMARY KEY (ID),
);
